Fix the problem described in issue #7
Corresponding error:
AttributeError: 'LineSegment' object has no attribute 'unit_vector'

An incomplete if module causes the problem. It is possible that the value of the variable 'self.length' is 0.0. In that case the attribute ’unit_vector‘ is not defined.